// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8EDHeoSc4qV4UnBikFWyHT
// Component: oRYFpcMkPh8Gx5Y
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Reviews from "../../Reviews"; // plasmic-import: FaEkFDeEuXo3Hko/component
import AsFeaturedIn from "../../AsFeaturedIn"; // plasmic-import: VziSSrlhKD5bawa/component
import ReviewCard from "../../ReviewCard"; // plasmic-import: eF4NWpQgcn5QqkT/component
import SideCta from "../../SideCta"; // plasmic-import: 3WVjthEJh54fw4F/component

import { useScreenVariants as useScreenVariantseb1C4W44VP2JBty } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Eb1c4W44vP2jBTY/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blog_quittinghacks_com.module.css"; // plasmic-import: 8EDHeoSc4qV4UnBikFWyHT/projectcss
import sty from "./PlasmicBlog.module.css"; // plasmic-import: oRYFpcMkPh8Gx5Y/css

export type PlasmicBlog__VariantMembers = {};
export type PlasmicBlog__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlog__VariantsArgs;
export const PlasmicBlog__VariantProps = new Array<VariantPropType>();

export type PlasmicBlog__ArgsType = {};
type ArgPropType = keyof PlasmicBlog__ArgsType;
export const PlasmicBlog__ArgProps = new Array<ArgPropType>();

export type PlasmicBlog__OverridesType = {
  root?: p.Flex<"div">;
  nav?: p.Flex<"div">;
  headline?: p.Flex<"div">;
  body?: p.Flex<"div">;
  asFeaturedIn?: p.Flex<typeof AsFeaturedIn>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  reviewCard?: p.Flex<typeof ReviewCard>;
  review2?: p.Flex<"div">;
  review3?: p.Flex<"div">;
  sideCta?: p.Flex<typeof SideCta>;
};

export interface DefaultBlogProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBlog__RenderFunc(props: {
  variants: PlasmicBlog__VariantsArgs;
  args: PlasmicBlog__ArgsType;
  overrides: PlasmicBlog__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantseb1C4W44VP2JBty()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "largestMobile")
              ? true
              : hasVariant(globalVariants, "screen", "smallestMobile")
              ? true
              : true
          ) ? (
            <div
              data-plasmic-name={"nav"}
              data-plasmic-override={overrides.nav}
              className={classNames(projectcss.all, sty.nav)}
            >
              <div className={classNames(projectcss.all, sty.columns__wiLns)}>
                <div className={classNames(projectcss.all, sty.column__fFaD2)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__lZpbH)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/blog_quittinghacks_com/images/logopng.png",
                      fullWidth: 276,
                      fullHeight: 46,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__qOUc1)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6T8Vb
                    )}
                  >
                    {'"The Evolution of Inhalation"'}
                  </div>
                </div>
              </div>
            </div>
          ) : null}

          <div
            data-plasmic-name={"headline"}
            data-plasmic-override={overrides.headline}
            className={classNames(projectcss.all, sty.headline)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ac7WF
              )}
            >
              {"Hard Hitting Zero-Nic Pods Pack Intense Mango or Mint Flavor!"}
            </div>

            <button
              className={classNames(
                projectcss.all,
                projectcss.button,
                projectcss.__wab_text,
                sty.button__guCDi
              )}
              disabled={false}
              link={
                "https://www.quittinghacks.com/rechargeable-offer/" as const
              }
            >
              {"CLAIM FREE PODS 👉"}
            </button>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nIfdd
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {"This new invention is turning \n"}
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"bad habits"}
                </span>
                <React.Fragment>{" into a "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"healthy ones"}
                </span>
                <React.Fragment>{"..."}</React.Fragment>
              </React.Fragment>
            </div>

            <Reviews
              className={classNames("__wab_instance", sty.reviews__sjgm5)}
            />

            {true ? (
              <div className={classNames(projectcss.all, sty.columns__tsCyp)}>
                <div className={classNames(projectcss.all, sty.column__z2Zwj)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ztLa1)}
                    displayHeight={"19px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"123px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/blog_quittinghacks_com/images/starpng2.png",
                      fullWidth: 142,
                      fullHeight: 21,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__mq2Gp)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kgMJ
                    )}
                  >
                    {"Rated 4.9 Stars By 100,000+ Customers"}
                  </div>
                </div>
              </div>
            ) : null}
          </div>

          {true ? (
            <div
              data-plasmic-name={"body"}
              data-plasmic-override={overrides.body}
              className={classNames(projectcss.all, sty.body)}
            >
              <AsFeaturedIn
                data-plasmic-name={"asFeaturedIn"}
                data-plasmic-override={overrides.asFeaturedIn}
                className={classNames("__wab_instance", sty.asFeaturedIn)}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__dtzAl)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                link={
                  "https://www.quittinghacks.com/rechargeable-offer/" as const
                }
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blog_quittinghacks_com/images/_9B498Fb8RechargableGif11Gif.gif",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nqKnx
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Imagine being nic-free but still getting that oh-so-satisfying throat hit along with delicious natural flavoring?\n\nIt almost sounds too good to be true, right? \n\nThe solution is simple... \n\nChoose natural ingredients, "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"NOT"}
                  </span>
                  <React.Fragment>
                    {" Stimulants and Harmful Chemicals:"}
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicLink
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                component={Link}
                href={
                  "https://www.quittinghacks.com/rechargeable-offer/" as const
                }
                platform={"nextjs"}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__pqI9)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blog_quittinghacks_com/images/screenshot20230224At43442PMpng.png",
                    fullWidth: 2352,
                    fullHeight: 802,
                    aspectRatio: undefined
                  }}
                />
              </p.PlasmicLink>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yXfnH
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Sparq Zero® is the evolution of inhalation. \n\nOur revolutionary diffuser comes in your choice of natural Sweet Mango or natural Cool Mint, providing you with the throat hit and intense flavoring you’re looking for... "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"without the guilt! "}
                  </span>
                  <React.Fragment>
                    {
                      "\n\nWe spent 6 years developing a device that was health-focused, lab-tested and that produced real throat hit and flavor that would effectively eliminate your cravings."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__x57Y0)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                link={
                  "https://www.quittinghacks.com/rechargeable-offer/" as const
                }
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blog_quittinghacks_com/images/fbfd287ERechargableGif21Gif.gif",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4H7Iv
                )}
              >
                {
                  "Absolutely no expense was spared with regard to design-form and function:\n\nThis ultra-modern metal device is slim, compact, odorless, and easy to use at any time or place."
                }
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ksP3)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blog_quittinghacks_com/images/_4B6E6Ed1Devicegif.gif",
                  fullWidth: 669,
                  fullHeight: 575,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zk759
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Plus it comes it comes in your choice of two delicious flavors, Sweet Mango or Cool Mint!\n\nWe even offer a "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"money-back guarantee"}
                  </span>
                  <React.Fragment>
                    {" if you don't absolutely love the taste and throat hit. "}
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__tlEo)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blog_quittinghacks_com/images/_6Bb5E2F0Image31000000000000000000028Png.png",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__baI6
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Most importantly, ALL of our formulations have undergone extensive lab-testing.\n\nThe test results verified our all-natural, plant-based pod ingredients are safe even when heated into a vapor.\n\n"
                    }
                  </React.Fragment>
                  {
                    <ul
                      className={classNames(
                        projectcss.all,
                        projectcss.ul,
                        sty.ul__pjsOw
                      )}
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li__uy3Lp
                        )}
                      >
                        {
                          "no harmful byproducts produced during the heating process (Gas chromatography)"
                        }
                      </li>
                    </ul>
                  }
                  <React.Fragment>{"\n"}</React.Fragment>
                  {
                    <ul
                      className={classNames(
                        projectcss.all,
                        projectcss.ul,
                        sty.ul__gd9Qk
                      )}
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li__tstX7
                        )}
                      >
                        {"no evidence of carbonyl compounds"}
                      </li>
                    </ul>
                  }
                  <React.Fragment>{"\n"}</React.Fragment>
                  {
                    <ul
                      className={classNames(
                        projectcss.all,
                        projectcss.ul,
                        sty.ul__nmHhS
                      )}
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          projectcss.__wab_text,
                          sty.li__hpaul
                        )}
                      >
                        {
                          "no evidence of “bad characters” known in the industry, including Diacetyl, Acrolein and Acetoin"
                        }
                      </li>
                    </ul>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__fnNki)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blog_quittinghacks_com/images/_12A7A7BbTestingSmallerImage10Yy0Fa0000000000000281Png.png",
                  fullWidth: 1258,
                  fullHeight: 550,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rrTbB
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Figure 1:"}
                  </span>
                  <React.Fragment>
                    {
                      " ISO-Accredited Laboratory certified safety and ensured the liquid remains stable even when heated."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uUmq4
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "We are incredibly proud to state that we have helped over 100,000 people quit while still allowing them to enjoy their habit, without any guilt!\n\nWe’ve made it easy for you to do the same, by offering a "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"FREE"}
                  </span>
                  <React.Fragment>
                    {
                      " box of our Sweet Mango or Cool Mint pods, with your first purchase, auto-applied at checkout."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___8JxB)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blog_quittinghacks_com/images/_7048E521Hit110000000000000000000281Png.png",
                  fullWidth: 614,
                  fullHeight: 332,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__em4Rt
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Click Here to Claim Free Sweet Mango or Cool Mint Pods!"}
                  </span>
                </React.Fragment>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gqMut
                )}
              >
                {"Fast Same Day Shipping"}
              </div>

              <div className={classNames(projectcss.all, sty.columns__a9ET)}>
                <div className={classNames(projectcss.all, sty.column__iHGc)}>
                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button__cKwYs
                    )}
                  >
                    {"CLAIM FREE PODS 👉"}
                  </button>
                </div>

                <div className={classNames(projectcss.all, sty.column__dtj5I)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ut5Kj)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/blog_quittinghacks_com/images/dividersvg.bin",
                      fullWidth: 5,
                      fullHeight: 150,
                      aspectRatio: 0.033333
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__acpE7)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3WkN
                    )}
                  >
                    {"100,000+ Happy Customers! In Stock - Ships Now."}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__g7XeA)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/blog_quittinghacks_com/images/starpng2.png",
                      fullWidth: 142,
                      fullHeight: 21,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___5Hqwc)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blog_quittinghacks_com/images/silverDeviceOutrogif.gif",
                  fullWidth: 669,
                  fullHeight: 575,
                  aspectRatio: undefined
                }}
              />
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "largestMobile")
              ? true
              : hasVariant(globalVariants, "screen", "smallestMobile")
              ? true
              : true
          ) ? (
            <div className={classNames(projectcss.all, sty.freeBox__a5Fqd)}>
              {true ? (
                <ReviewCard
                  data-plasmic-name={"reviewCard"}
                  data-plasmic-override={overrides.reviewCard}
                  className={classNames("__wab_instance", sty.reviewCard)}
                />
              ) : null}

              <div
                data-plasmic-name={"review2"}
                data-plasmic-override={overrides.review2}
                className={classNames(projectcss.all, sty.review2)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zgNo2)}
                  displayHeight={"100px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blog_quittinghacks_com/images/sidereview2Png.png",
                    fullWidth: 119,
                    fullHeight: 119,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cv3AS
                  )}
                >
                  {"Jason G."}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gGf5V)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blog_quittinghacks_com/images/starpng2.png",
                    fullWidth: 142,
                    fullHeight: 21,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__anFii
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"AWESOME"}
                    </span>
                  </React.Fragment>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7I2He
                  )}
                >
                  {
                    "“Excellent. I love this. I quit cigs and went to the sparq. I love this device. It is natural, no nic. It really does help calm me.”"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"review3"}
                data-plasmic-override={overrides.review3}
                className={classNames(projectcss.all, sty.review3)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___07Ae8)}
                  displayHeight={"100px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blog_quittinghacks_com/images/sidereview3Png.png",
                    fullWidth: 119,
                    fullHeight: 119,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pHyrz
                  )}
                >
                  {"Kathy B"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mHaA)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blog_quittinghacks_com/images/starpng2.png",
                    fullWidth: 142,
                    fullHeight: 21,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1VUby
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"LOVE! LOVE!!"}
                    </span>
                  </React.Fragment>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0246G
                  )}
                >
                  {
                    "“Im literally obsessed the the elegant\ndesign as well as the jaw dropping\npackaging.”"
                  }
                </div>
              </div>

              <SideCta
                data-plasmic-name={"sideCta"}
                data-plasmic-override={overrides.sideCta}
                className={classNames("__wab_instance", sty.sideCta)}
              />
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "nav",
    "headline",
    "body",
    "asFeaturedIn",
    "link",
    "reviewCard",
    "review2",
    "review3",
    "sideCta"
  ],
  nav: ["nav"],
  headline: ["headline"],
  body: ["body", "asFeaturedIn", "link"],
  asFeaturedIn: ["asFeaturedIn"],
  link: ["link"],
  reviewCard: ["reviewCard"],
  review2: ["review2"],
  review3: ["review3"],
  sideCta: ["sideCta"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  nav: "div";
  headline: "div";
  body: "div";
  asFeaturedIn: typeof AsFeaturedIn;
  link: "a";
  reviewCard: typeof ReviewCard;
  review2: "div";
  review3: "div";
  sideCta: typeof SideCta;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlog__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlog__VariantsArgs;
    args?: PlasmicBlog__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlog__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBlog__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlog__ArgProps,
          internalVariantPropNames: PlasmicBlog__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicBlog__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlog";
  } else {
    func.displayName = `PlasmicBlog.${nodeName}`;
  }
  return func;
}

export const PlasmicBlog = Object.assign(
  // Top-level PlasmicBlog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    headline: makeNodeComponent("headline"),
    body: makeNodeComponent("body"),
    asFeaturedIn: makeNodeComponent("asFeaturedIn"),
    link: makeNodeComponent("link"),
    reviewCard: makeNodeComponent("reviewCard"),
    review2: makeNodeComponent("review2"),
    review3: makeNodeComponent("review3"),
    sideCta: makeNodeComponent("sideCta"),

    // Metadata about props expected for PlasmicBlog
    internalVariantProps: PlasmicBlog__VariantProps,
    internalArgProps: PlasmicBlog__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBlog;
/* prettier-ignore-end */
